import path from 'node:path';
import { readFile, writeFile } from 'node:fs/promises';
import { demo, scenes } from './common.mjs';
const narration = JSON.parse(await readFile(path.join(demo,'storyboard/narration.json'),'utf8'));
let offset=0;
const rows=narration.segments.map(segment=>{
  const seconds=segment.id==='intro'?narration.introSeconds:segment.id==='outro'?narration.outroSeconds:scenes.find(scene=>scene.id===segment.id).seconds;
  const time=`${String(offset).padStart(2,'0')}-${String(offset+seconds).padStart(2,'0')}`;
  offset+=seconds;
  return `| ${time}s | ${segment.id} | ${segment.lines.join(' ')} |`;
});
await writeFile(path.join(demo,'storyboard/narration-script.md'),`# LOCALHOST: LEVEL UP - narration\n\nCurrent creative revision 4. ${offset} seconds. Generic synthetic English voice, burned-in measured sentence subtitles and external SRT.\n\n| Target time | Segment | Spoken copy |\n| --- | --- | --- |\n${rows.join('\n')}\n\nThe generator reads narration.json. Exact final spoken/caption timing is measured and exported to public/assets/captions.json and output/project-montage-level-up.srt. The original backing music is 112 BPM; synthesized click/readiness/typing effects use captured event times and processed clip speed.\n`);
await writeFile(path.join(demo,'storyboard/storyboard.md'),`# LOCALHOST: LEVEL UP - creative revision 4\n\nA ${offset}-second 1920 x 1080, 30 FPS advertising cut for casual developers and side-project builders. Navy, mint, violet; kinetic typography, perspective dashboard cards, a playful terminal/port hook, focused real app footage, hover glow, a visible illustrated cursor, click ripples, actual local browser previews, benefit layouts, seven-part progress and highlighted sentence subtitles.\n\nThe full creative treatment is [creative-ad-script.md](../../docs/showcase/creative-ad-script.md). Spoken copy is [narration-script.md](narration-script.md).\n\n${rows.join('\n')}\n\n## Capture evidence\n\nAll feature footage comes from real Electron in dedicated user data with fictional generated projects. Actual IPC, discovery, Windows process ownership, HTTP readiness, logs, search/filter and theme actions are retained. npm and HTML preview screenshots come from their actual verified local servers in isolated Chromium. OS browser launching is intercepted during recording; no ordinary user tabs or catalog are read. The native picker is stubbed.\n\nPaths are redacted. Hover styling, pointer and ripples are capture-only editorial effects. Terminal illustrations, framing, chapter icons and animated headlines are editorial graphics. Startup waits are condensed and labeled. Sharing opens and cancels the real access/compatibility confirmation; no public tunnel is started and its footage is labeled accordingly. Normal quit cleanup is verified.\n\n## Audio and exports\n\nLocal Kokoro generic synthetic voice; original procedural 112 BPM electronic music; original synthesized clicks, taps, typing, readiness/link chimes and sweeps. Music ducks beneath speech. Captions use measured sentence audio, not guessed word timing.\n\nNamed video: output/project-montage-level-up.mp4. Named captions: output/project-montage-level-up.srt. Existing alias exports remain. Prior marketing video/SRT are preserved as project-montage-marketing-r3.*, with prior source under archives/revision-3/.\n\nQA checks TypeScript, full media decode, H.264/AAC streams, resolution, frame rate, duration, audio headroom, subtitle content/timing, and representative final frames. Visual review must inspect the final frames after each regeneration. Windows source-build preview status remains visible; no installer, universal framework/platform support, permanent hosting, or open-source license availability is claimed.\n`);
