import { afterEach, expect, it, vi } from 'vitest';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { Persistence, emptyState } from '../src/main/services/persistence';
import { themes } from '../src/shared/contracts';
import { AppService } from '../src/main/services/appService';
import { LogManager } from '../src/main/services/logManager';
import { dispose, fixtureDirectory, packageFile, root } from './helpers';

const fixtures: string[] = [];
it('excludes release subtrees, removes cached copies, preserves same-name sources and supports re-inclusion', async () => {
  const directory = await fixtureDirectory(); fixtures.push(directory);
  const app = path.join(directory, 'projects', 'app');
  const releases = path.join(app, 'data', 'releases');
  const release = path.join(releases, '123-copy', 'app');
  const similarlyNamed = path.join(app, 'data', 'releases-other');
  for (const folder of [app, release, similarlyNamed]) await packageFile(folder, { name: 'same-name', scripts: { dev: 'node server.js' } });
  const persistence = new Persistence(path.join(directory, 'state'));
  const service = new AppService(persistence, () => {}); await service.initialize(); await service.addRoot(path.join(directory, 'projects'));
  expect(service.snapshot().projects).toHaveLength(3);
  await service.addExclusion(releases);
  expect(service.snapshot().projects.map((item) => item.path)).toEqual(expect.arrayContaining([app, similarlyNamed]));
  expect(service.snapshot().projects).toHaveLength(2);
  expect(await readFile(path.join(release, 'package.json'), 'utf8')).toContain('same-name');
  const restored = new AppService(persistence, () => {}); await restored.initialize(); await restored.scan();
  expect(restored.snapshot().projects).toHaveLength(2);
  const exclusion = restored.snapshot().exclusions.find((item) => item.path === releases)!;
  await restored.removeExclusion(exclusion.id);
  expect(restored.snapshot().projects).toHaveLength(3);
  await expect(restored.removeExclusion(exclusion.id)).rejects.toThrow('not found');
});
it('retains actively managed excluded entries, blocks new starts and removes them once inactive', async () => {
  const directory = await fixtureDirectory(); fixtures.push(directory);
  const project = path.join(directory, 'projects', 'release');
  await packageFile(project, { scripts: { dev: 'node server.js' } });
  const service = new AppService(new Persistence(path.join(directory, 'state')), () => {});
  await service.initialize(); await service.addRoot(path.join(directory, 'projects'));
  const id = service.snapshot().projects[0]!.id;
  const active = vi.spyOn(service.processes, 'isActive').mockReturnValue(true);
  await service.addExclusion(project);
  expect(service.snapshot().projects).toHaveLength(1);
  expect(service.snapshot().diagnostics.join(' ')).toContain('retained until stopped');
  await expect(service.start(id)).rejects.toThrow('excluded');
  active.mockReturnValue(false); await service.scan();
  expect(service.snapshot().projects).toHaveLength(0);
  active.mockRestore();
});
it('migrates legacy state to generic defaults and preserves an explicitly empty list', async () => {
  const directory = await fixtureDirectory(); fixtures.push(directory);
  const persistence = new Persistence(directory);
  await writeFile(persistence.file, JSON.stringify({ version: 1, roots: [], projects: [], theme: 'dark' }));
  expect((await persistence.load()).state.exclusions).toEqual([]);
  await persistence.save({ ...emptyState(), exclusions: [] });
  expect((await persistence.load()).state.exclusions).toEqual([]);
});
afterEach(async () => { for (const directory of fixtures.splice(0)) await dispose(directory); });
it('serializes concurrent atomic saves and recovers a damaged primary from backup', async () => {
  const directory = await fixtureDirectory(); fixtures.push(directory);
  const persistence = new Persistence(directory);
  const initial = { ...emptyState(), roots: [root(directory)] };
  await persistence.save(initial);
  await Promise.all([persistence.save({ ...initial, settings: { ...initial.settings, appearance: { ...initial.settings.appearance, theme: 'dark' } } }), persistence.save({ ...initial, settings: { ...initial.settings, appearance: { ...initial.settings.appearance, theme: 'light' } } })]);
  expect((await persistence.load()).state.settings.appearance.theme).toBe('light');
  await writeFile(persistence.file, 'invalid json');
  const restored = await persistence.load();
  expect(restored.state.settings.appearance.theme).toBe('dark'); expect(restored.warning).toContain('Recovered');
  await persistence.save(restored.state);
  await writeFile(persistence.file, 'damaged again');
  expect((await persistence.load()).state.settings.appearance.theme).toBe('dark');
});
it('keeps roots and cached metadata across launches, resets runtime, and retains missing projects', async () => {
  const directory = await fixtureDirectory(); fixtures.push(directory);
  const projects = path.join(directory, 'projects');
  await packageFile(path.join(projects, 'web'), { scripts: { dev: 'node server.js' } });
  const persistence = new Persistence(path.join(directory, 'state'));
  const first = new AppService(persistence, () => {}); await first.initialize(); await first.addRoot(projects);
  expect(first.snapshot().projects).toHaveLength(1);
  await expect(first.addRoot(projects)).rejects.toThrow('already registered');
  const second = new AppService(persistence, () => {}); await second.initialize();
  expect(second.snapshot().roots[0]?.path).toBe(projects);
  expect(second.snapshot().projects[0]?.status).toBe('stopped');
  await writeFile(path.join(projects, 'web/package.json'), JSON.stringify({ scripts: {} }));
  await second.scan(); expect(second.snapshot().projects[0]?.missing).toBe(true);
  await second.removeRoot(second.snapshot().roots[0]!.id);
  expect(second.snapshot().projects).toEqual([]);
  expect(await readFile(path.join(projects, 'web/package.json'), 'utf8')).toContain('scripts');
});
it('bounds logs by lines, bytes and global budget while stripping ANSI control sequences', () => {
  const logs = new LogManager(() => {}, 3, 40, 50);
  logs.append('one', 'stdout', '\x1b[31mhello\x1b[0m\nline 2\nline 3\nline 4');
  expect(logs.get('one').map((item) => item.text)).toEqual(['line 2', 'line 3', 'line 4']);
  logs.append('two', 'stderr', 'x'.repeat(35));
  const all = [...logs.get('one'), ...logs.get('two')];
  expect(all.reduce((sum, item) => sum + Buffer.byteLength(item.text), 0)).toBeLessThanOrEqual(50);
  logs.clear('two'); expect(logs.get('two')).toEqual([]);
});

it.each(themes)('restores the $label appearance across application launches', async ({ value }) => {
  const directory = await fixtureDirectory(); fixtures.push(directory);
  const persistence = new Persistence(directory);
  const service = new AppService(persistence, () => {});
  await service.initialize();
  await service.updateSettings({ appearance: { theme: value } });
  const restored = new AppService(persistence, () => {});
  await restored.initialize();
  expect(restored.snapshot().settings.appearance.theme).toBe(value);
});